const computers = [
    {
        image : "./pcImages/white_grigs.png",
        name : "G:RIGS > White Version",
        price : 1919,
        cpu : "AMD Ryzen 5 5500",
        gpu : "GeForce RTX 3050",
        mb : "MSI B450 TOMAHAWK MAX II",
        psu : "EVGA 750 GQ Gold 750W",
        color : "Бял",
        type : "G:RIGS",
    },
    {
        image : "./pcImages/blackout_grigs.png",
        name : "G:RIGS > Blackout",
        price : 1999,
        cpu : "Intel Core i5-11400F",
        gpu : "GeForce RTX 2060",
        mb : "MSI B560M PRO-VDH",
        psu : "EVGA 500 BR Bronze 500W",
        color : "Черен",
        type : "G:RIGS",

    },
    {
        image : "./pcImages/grigs_esports.png",
        name : "G:RIGS > Esports",
        price : 1879,
        cpu : "Intel Core i5-11400F",
        gpu : "GeForce RTX 2060",
        mb : "MSI B560M PRO-VDH",
        psu : "EVGA 500 BR Bronze 500W",
        color : "Бял",
        type : "G:RIGS",
    },
    {
        image : "./pcImages/grigs_challenger.jpg",
        name : "G:RIGS > Challenger",
        price : 1449,
        cpu : "AMD Ryzen 5 4500",
        gpu : "GeForce GTX 1650",
        mb : "MSI B450M PRO-VDH MAX",
        psu : "Cougar VTE 500W Bronze",
        color : "Черен",
        type : "G:RIGS",
    },
    {
        image : "./pcImages/grigs_libra.png",
        name : "G:RIGS > Libra",
        price : 1439,
        cpu : "AMD Ryzen 5 4500",
        gpu : "MSI GeForce GTX 1650 VENTUS XS 4G OC",
        mb : "ASUS TUF GAMING B450-PLUS II",
        psu : "be quiet! System Power 9 Bronze 500W",
        color : "Бял",
        type : "G:RIGS",
    },
    {
        image : "./pcImages/grigs_recon.jpg",
        name : "G:RIGS > Recon",
        price : 1799,
        cpu : "Intel Core i5-11400F",
        gpu : "GeForce GTX 1650",
        mb : "ASUS TUF GAMING B450-PLUS II",
        psu : "EVGA SuperNOVA 550 GT Gold 550W",
        color : "Черен",
        type : "G:RIGS",
    },
    {
        image : "./pcImages/grigs_commander.jpg",
        name : "G:RIGS > Commander",
        price : 2700,
        cpu : "AMD Ryzen 5 5500",
        gpu : "RTX 3070 Ti",
        mb : "ASUS TUF GAMING B450-PLUS II",
        psu : "EVGA SuperNOVA 550 GT Gold 550W",
        color : "Черен",
        type : "G:RIGS",
    }
]